title: Clojure4Beginners
author:
  name: Rubber Ducks

#description: >
# 

theme: minima
minima:
  skin: classic
  header_pages:
    - README.md
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/rubberducksbr"
    - title: Instagram
      icon: instagram
      url: "https://instagram.com/rubberducksbr"
